name: dyg
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.1
  flutter_web_auth: ^0.4.1
  pkce: ^1.1.0+1
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  auto_size_text: ^3.0.0
  flutter_svg: ^1.1.4
  flutter_secure_storage: ^6.0.0
  encrypt: ^5.0.1
  url_launcher: ^6.1.5
  just_audio: ^0.9.29

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/bg-design.svg
    - assets/images/onboarding/center-image.png
    - assets/images/onboarding/button.svg

    - assets/images/login/bg-design.svg
    - assets/images/login/center-image.png
    - assets/images/login/button.svg

    - assets/images/personalization/bg-design.svg
    - assets/images/personalization/trial.png

    - assets/images/recommendations/bg-design.svg

    - assets/images/no_internet.jpg
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
    - family: SyneBold
      fonts:
        - asset: assets/fonts/Syne-Bold.ttf
